### ISSUE TITLE
[Bug]: Ultrawide not working if monitor is set as secondary display in windows.

### ISSUE THREAD

**Issue by Aaron-Strong** [Lyall/GBFRelinkFix#28]
## Issue Summary:
Ultrawide not working if monitor is set as secondary display in windows.

## GBFRelinkFix & Game Version Numbers:
v1.0.4 of gran & your fix

## Log Files:
I don't see a log file 😩

## Reproduction:
- Set ultrawide monitor as secondary display in windows
- Change to ultrawide monitor in gran's settings

Restarting the game doesn't help.
Swapping the ultrawide to the primary display resolves the issue but is awful QOL

Thanks for any help and for making such a good mod ^^

**Comment by Lyall** [comment]
Sorry for the late reply but has the mod worked at all for you? You should be getting a `GBFRelinkFix.log` file.

**Comment by Aaron-Strong** [comment]
Oh my god I'm so stupid. New pc and I didn't have file extensions showing anymore X_X
[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14317041/GBFRelinkFix.log)

There's a fresh log with the ultrawide set as secondary display in windows, and selected in gran's settings.

**Comment by Lyall** [comment]
Okay so when `iCustomResX` and `iCustomResY` are set to 0 in the config file then your desktop resolution for your primary display is used. Since the function I use only pulls info from the primary display, a solution for you might be to enter the resolution of your ultrawide display in the config file. 

For example if your ultrawide display is 5120x1440 then you would set it like this:
```ini
[Custom Resolution]
; Enter your chosen resolution.
; You can leave these at 0 if you want your desktop resolution used instead.
Enabled = true
Width = 5120
Height = 1440
```

**Comment by Aaron-Strong** [comment]
That worked great. Thank you for the assistance and for your great work!
