### ISSUE TITLE
[Bug]: Black bar appearing in battle cutscene 16:10

### ISSUE THREAD

**Issue by Sindd22** [Lyall/GBFRelinkFix#42]
## Issue Summary:

Theres always this weird bar just like in the picture, even worse in lucilius quest, every cutscene will show this bar and it appear multiple times. 

![granblue_fantasy_relink 2024-03-15 01-19-31](https://github.com/Lyall/GBFRelinkFix/assets/163448956/93a0db9e-9c4a-4bf3-a5ad-b3c903cdc749)

my laptop aspect ratio is 16:10

and i never have this problem back then using 1.0 fix.
now every mission shows this bar in cutscene.

**Comment by Vaadwaur278** [comment]
I also have this issue on my steam deck. Have you also tried fighting Proto Bahamut too? The effects aren't aligned correctly when he's summoning crystals. Never had this problem when I was on 1.0.4 and my .ini are all stock.

![download](https://github.com/Lyall/GBFRelinkFix/assets/145878996/39309fd5-9657-4e59-88af-814fef0cadb4)

**Comment by Sindd22** [comment]
> I also have this issue on my steam deck. Have you also tried fighting Proto Bahamut too? The effects aren't aligned correctly when he's summoning crystals. Never had this problem when I was on 1.0.4 and my .ini are all stock.
> 
> ![download](https://private-user-images.githubusercontent.com/145878996/312945514-39309fd5-9657-4e59-88af-814fef0cadb4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzkxNDMsIm5iZiI6MTcxMDQzODg0MywicGF0aCI6Ii8xNDU4Nzg5OTYvMzEyOTQ1NTE0LTM5MzA5ZmQ1LTk2NTctNGU1OS04OGFmLTgxNGZlZjBjYWRiNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTc1NDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZjYzQxZmExMGMzNzNlYTNkNTMzOGY1Y2M3MGZlZDRmMGMxOWNiYWMxZmI3ZjdjNGQ4NjFhOTIzMDg4NWQ0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IEeh8KXDqQ3p_EdgCFoZYOlAT9VnJ4N7_DQcQYzxhLE)

yeah even worse it happens on every quest that i tried...pyet, versa, proto...

**Comment by Lyall** [comment]
Can you try out this test build?

[GBFRelinkFix_v1.0.9_test.zip](https://github.com/Lyall/GBFRelinkFix/files/14606249/GBFRelinkFix_v1.0.9_test.zip)

If that doesn't work, can you upload your save file? I'm still very early game so I don't have access to these end-game fights. The save data is stored in `%LOCALAPPDATA%\GBFR\Saved\SaveGames\`

**Comment by Sindd22** [comment]
> Can you try out this test build?
> 
> [GBFRelinkFix_v1.0.9_test.zip](https://github.com/Lyall/GBFRelinkFix/files/14606249/GBFRelinkFix_v1.0.9_test.zip)
> 
> If that doesn't work, can you upload your save file? I'm still very early game so I don't have access to these end-game fights. The save data is stored in `%LOCALAPPDATA%\GBFR\Saved\SaveGames\`

it doesnt work, same result, 
![granblue_fantasy_relink 2024-03-15 02-16-46](https://github.com/Lyall/GBFRelinkFix/assets/163448956/dacf59ba-0474-420e-8dde-db4280c8821d)

 and here extreme mission ice dragon, it still a problem in low difficulty mission
![granblue_fantasy_relink 2024-03-15 02-22-31](https://github.com/Lyall/GBFRelinkFix/assets/163448956/7fa62c67-9bec-46b2-8da1-337313c987e5)

it seems it doesnt scale properly to 16:10

**Comment by Vaadwaur278** [comment]
> Can you try out this test build?
> 
> [GBFRelinkFix_v1.0.9_test.zip](https://github.com/Lyall/GBFRelinkFix/files/14606249/GBFRelinkFix_v1.0.9_test.zip)
> 
> If that doesn't work, can you upload your save file? I'm still very early game so I don't have access to these end-game fights. The save data is stored in `%LOCALAPPDATA%\GBFR\Saved\SaveGames\`

Same issue as before
![download](https://github.com/Lyall/GBFRelinkFix/assets/145878996/6a82b9f0-4a3a-417f-9873-a0e1b8f29a78)
[SaveData1.zip](https://github.com/Lyall/GBFRelinkFix/files/14606684/SaveData1.zip)

**Comment by Glfz65** [comment]
this bug started in v1.0.8 (io's circle fix)
so i think it will go away if we temporaril return to v1.0.7 ? perhaps

**Comment by Lyall** [comment]
Alright I think there's maybe two bugs here. The first being the overlays being 16:9 and offset. That issue I believe is being caused by the game switching between 4K and 1080P HUD elements if your horizontal resolution is lower than 1920. As for the second issue of the effects, that may well have been caused by the work in #35.

**Comment by Lyall** [comment]
Okay, sorry for the delay on this. So the issue is linked to #35 and the work done for that issue. I've been looking at it further and it's kind of complex. It seems like some of the screen effects, like low health or the flash/orb when you use Io's primary attack are specifically designed for 16:9. 

So there's two options, either they are display at 16:9 which results in black bars on certain effects but retains the correct aspect ratio, or they are rendered at a wider aspect ratio that eliminates black bars but results in some squashed effects. 

I have gone with the latter option for the latest [v1.1.0 release](https://github.com/Lyall/GBFRelinkFix/releases). This should address the issues in #42 and #43. 

I do plan on trying to get both issues fixed at the same time in the future but for now I don't think it's possible.

**Comment by Sindd22** [comment]
my problem is fixed with this new build.
Thanks so much Lyall
